apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: fastcgi
  name: fastcgi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: fastcgi
    spec:
      containers:
      - image: femiwiki/mediawiki:build-29
        name: fastcgi
        resources: {}
        volumeMounts:
        - mountPath: /a
          name: fastcgi-claim0
          readOnly: true
        - mountPath: /srv/femiwiki.com
          name: files
        - mountPath: /tmp/cache
          name: l18n-cache
      restartPolicy: Always
      volumes:
      - name: fastcgi-claim0
        persistentVolumeClaim:
          claimName: fastcgi-claim0
          readOnly: true
      - name: files
        persistentVolumeClaim:
          claimName: files
      - name: l18n-cache
        persistentVolumeClaim:
          claimName: l18n-cache
status: {}
