apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@femiwiki.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-letsencrypt-staging
    solvers:
      - dns01:
          route53:
            region: ap-northeast-1
            hostedZoneID: Z1IOLPZGUQYUUT
            role: arn:aws:iam::302617221463:role/Femiwiki
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@femiwiki.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: ap-northeast-1
            hostedZoneID: Z1IOLPZGUQYUUT
            role: arn:aws:iam::302617221463:role/Femiwiki
