apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastcgi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastcgi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fastcgi
    spec:
      containers:
      - image: femiwiki/mediawiki:build-29
        name: fastcgi
        volumeMounts:
        - mountPath: /a
          name: fastcgi-claim0
          readOnly: true
        - mountPath: /srv/femiwiki.com
          name: files
        - mountPath: /tmp/cache
          name: l18n-cache
      restartPolicy: Always
      volumes:
      - name: fastcgi-claim0
        persistentVolumeClaim:
          claimName: fastcgi-claim0
          readOnly: true
      - name: files
        persistentVolumeClaim:
          claimName: files
      - name: l18n-cache
        persistentVolumeClaim:
          claimName: l18n-cache
