apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastcgi
spec:
  selector:
    matchLabels:
      app: fastcgi
  template:
    metadata:
      labels:
        app: fastcgi
    spec:
      containers:
      - image: femiwiki/mediawiki:build-29
        name: fastcgi
        volumeMounts:
        - mountPath: /srv/femiwiki.com
          name: files
        - mountPath: /tmp/cache
          name: l18n-cache
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: files
      - name: l18n-cache
        persistentVolumeClaim:
          claimName: l18n-cache
