apiVersion: v1
kind: Pod
metadata:
  name: http
spec:
  containers:
  - env:
    - name: CADDYPATH
      value: /etc/caddycerts
    image: femiwiki/caddy:1.0.3
    name: http
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /srv/femiwiki.com
      name: files
    - mountPath: /etc/caddycerts
      name: caddy
  restartPolicy: OnFailure
  volumes:
  - name: files
    persistentVolumeClaim:
      claimName: files
  - name: caddy
    persistentVolumeClaim:
      claimName: caddy
