apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: femiwiki
        # NOTE: 개발용으로만 사용되는 옵션이고 실제 프로덕션에서는 무시되는 옵션들임
        - name: MYSQL_PASSWORD
          value: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          value: localfemiwikipassword
        - name: MYSQL_USER
          value: DB_USERNAME
        image: mysql:8.0.17
        name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: database
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
