apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: femiwiki
        - name: MYSQL_PASSWORD
          value: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          value: localfemiwikipassword
        - name: MYSQL_USER
          value: DB_USERNAME
        image: mysql:8.0.17
        name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: database
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database

