apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsoid
spec:
  selector:
    matchLabels:
      app: parsoid
  template:
    metadata:
      labels:
        app: parsoid
    spec:
      containers:
      - name: parsoid
        image: femiwiki/parsoid:build-1
---
# TODO: 서비스 만들기
