apiVersion: v1
kind: Namespace
metadata:
  name: parsoid
  nampspace: parsoid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsoid
  nampspace: parsoid
spec:
  selector:
    matchLabels:
      app: parsoid
  template:
    metadata:
      labels:
        app: parsoid
    spec:
      containers:
      - name: parsoid
        image: femiwiki/parsoid:build-1
---
apiVersion: v1
kind: Service
metadata:
  name: parsoid
  namespace: parsoid
spec:
  ports:
  - name: parsoid
    port: 8000
    targetPort: 8000
  selector:
    app: parsoid
