apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fastcgi
  namespace: femiwiki
  annotations:
    cert-manager.io/cluster-issuer:
    ingress.kubernetes.io/force-hsts: "false"
    ingress.kubernetes.io/hsts-include-subdomains: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: http
              servicePort: 80
          # Proxy requests to RESTBase
          # Reference:
          #   https://www.mediawiki.org/wiki/RESTBase/Installation#Proxy_requests_to_RESTBase_from_your_webserver
          - path: /femiwiki.com
            backend:
              serviceName: restbase
              servicePort: 7231
  tls:
