apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: femiwiki-com
  namespace: femiwiki
spec:
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
    - test.femiwiki.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fastcgi
  namespace: femiwiki
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: http
              servicePort: 80
          # Proxy requests to RESTBase
          # Reference:
          #   https://www.mediawiki.org/wiki/RESTBase/Installation#Proxy_requests_to_RESTBase_from_your_webserver
          - path: /femiwiki.com
            backend:
              serviceName: restbase
              servicePort: 7231
