apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: femiwiki
data:
  Caddyfile: |
    *:80
    tls off
    root /srv/femiwiki.com
    index index.php
    fastcgi / localhost:9000 php
    gzip
    header / {
      # Enable XSS filtering for legacy browsers
      X-XSS-Protection "1; mode=block"
      # Block content sniffing, and enable Cross-Origin Read Blocking
      X-Content-Type-Options "nosniff"
      # Avoid clickjacking
      X-Frame-Options "DENY"
    }
    rewrite /w/api.php {
      to /api.php
    }
    rewrite /w {
      r  /(.*)
      to /index.php
    }
