## TODO: secret.php 등은 https://github.com/bitnami-labs/sealed-secrets 관리하기

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: femiwiki-com
  namespace: femiwiki
spec:
  secretName: acme-crt-secret
  dnsNames:
  - '*.femiwiki.com'
  - femiwiki.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  # TODO Add HSTS header
  name: fastcgi
  namespace: femiwiki
spec:
  rules:
    - host: femiwiki.com
      http:
        paths:
          - backend:
              serviceName: http
              servicePort: 80
          # Proxy requests to RESTBase
          # Reference:
          #   https://www.mediawiki.org/wiki/RESTBase/Installation#Proxy_requests_to_RESTBase_from_your_webserver
          - path: /femiwiki.com
            backend:
              serviceName: restbase
              servicePort: 7231
  tls:
    - hosts:
        - femiwiki.com
        - "*.femiwiki.com"
      secretName: acme-crt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: femiwiki
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: fastcgi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastcgi
  namespace: femiwiki
spec:
  selector:
    matchLabels:
      app: fastcgi
  template:
    metadata:
      labels:
        app: fastcgi
    spec:
      initContainers:
        # https://stackoverflow.com/questions/57061680 solution
        - name: init-fastcgi
          image: femiwiki/mediawiki:2020-03-27T13-48d5c3bd9a
          volumeMounts:
            - name: fastcgi
              mountPath: /share
          command: [cp, -a, /srv/femiwiki.com, /share]
        - name: init-cache
          image: femiwiki/mediawiki:2020-03-27T13-48d5c3bd9a
          volumeMounts:
            - name: l18n-cache
              mountPath: /tmp/cache
          command: ["sh", "-c", "chown -R www-data:www-data /tmp/cache"]
      containers:
        - name: fastcgi
          image: femiwiki/mediawiki:2020-03-27T13-48d5c3bd9a
          volumeMounts:
            - name: mediawiki-configs
              mountPath: /a/
              readOnly: true
        - name: http
          image: femiwiki/caddy:1.0.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: fastcgi
              mountPath: /srv
              readOnly: true
            - name: caddyfile
              mountPath: /etc/Caddyfile
              subPath: Caddyfile
              readOnly: true
            - name: caddycerts
              mountPath: /etc/caddycerts

      volumes:
        - name: fastcgi
          emptyDir: {}
        - name: mediawiki-configs
          projected:
            sources:
              - configMap:
                  name: local-settings
                  items:
                    - key: local-settings
                      path: LocalSettings.php
              - secret:
                  name: secret-local-settings
                  items:
                    - key: secret
                      path: secret.php
              - configMap:
                  name: sitelist
                  items:
                    - key: sitelist
                      path: sitelist.xml
        - name: l18n-cache
          hostPath:
            path: /srv/femiwiki.com/l18n-cache
            type: DirectoryOrCreate
        - name: caddyfile
          configMap:
            name: caddyfile
        - name: caddycerts
          hostPath:
            path: /srv/femiwiki.com/caddycerts
            type: DirectoryOrCreate
