apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: femiwiki
spec:
  ports:
  - name: memcached
    port: 11211
    targetPort: 11211
  selector:
    app: memcached
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: femiwiki
spec:
  serviceName: memcached
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - image: memcached:1-alpine
        name: memcached
