# TODO: Statefulset으로 고치기
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: femiwiki
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        args:
        - --default-authentication-plugin=mysql_native_password
        image: mysql:8.0.17
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: database
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: femiwiki
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: femiwiki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # TODO: 사이즈 확정하기
      storage: 100Mi
