apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: femiwiki
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: femiwiki
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        args:
        - --default-authentication-plugin=mysql_native_password
        image: mysql:8.0.19
        volumeMounts:
        - mountPath: /var/lib/mysql
          # TODO: https://github.com/upnl/kubernetes/pull/10 이 문제가 재발하지 않는지 검사하기
          name: mysql
      volumes:
      - name: mysql
        hostPath:
          path: /srv/femiwiki.com/mysql
          type: DirectoryOrCreate
