apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsoid
  namespace: femiwiki
spec:
  selector:
    matchLabels:
      app: parsoid
  template:
    metadata:
      labels:
        app: parsoid
    spec:
      containers:
        - name: parsoid
          image: femiwiki/parsoid:20200323051655dc3862
---
apiVersion: v1
kind: Service
metadata:
  name: parsoid
  namespace: femiwiki
spec:
  ports:
    - name: parsoid
      port: 8000
      targetPort: 8000
  selector:
    app: parsoid
